import { SpellData } from './types';

export const spellsData: SpellData = {
  "Classic": {
    "General": [
      { "name": "PVP Trinket", "imageUrl": "zamimg-icons/inv_jewelry_trinketpvp_02.jpg" },
      { "name": "Will of the Forsaken", "imageUrl": "zamimg-icons/spell_shadow_raisedead.jpg" },
      { "name": "Stoneform", "imageUrl": "zamimg-icons/spell_shadow_unholystrength.jpg" },
      { "name": "Escape Artist", "imageUrl": "zamimg-icons/spell_shadow_charm.jpg" },
      { "name": "Perception", "imageUrl": "zamimg-icons/spell_nature_sleep.jpg" },
      { "name": "Shadowmeld", "imageUrl": "zamimg-icons/ability_ambush.jpg" },
      { "name": "War Stomp", "imageUrl": "zamimg-icons/ability_warstomp.jpg" },
      { "name": "Berserking", "imageUrl": "zamimg-icons/racial_troll_berserk.jpg" }
    ],
    "Warrior": [
      { "name": "Charge", "imageUrl": "zamimg-icons/spell_charge.jpg" },
      { "name": "Battle Shout", "imageUrl": "zamimg-icons/spell_battle_shout.jpg" },
      { "name": "Rend", "imageUrl": "zamimg-icons/ability_gouge.jpg" },
      { "name": "Execute", "imageUrl": "zamimg-icons/inv_sword_48.jpg" },
      { "name": "Sunder Armor", "imageUrl": "zamimg-icons/spell_fire_firearmor.jpg" },
      { "name": "Heroic Strike", "imageUrl": "zamimg-icons/ability_rogue_ambush.jpg" },
      { "name": "Thunder Clap", "imageUrl": "zamimg-icons/spell_nature_thunderclap.jpg" },
      { "name": "Demoralizing Shout", "imageUrl": "zamimg-icons/classic_ability_druid_demoralizingroar.jpg" },
      { "name": "Cleave", "imageUrl": "zamimg-icons/spell_cleave.jpg" },
      { "name": "Hamstring", "imageUrl": "zamimg-icons/ability_shockwave.jpg" },
      { "name": "Mocking Blow", "imageUrl": "zamimg-icons/ability_warrior_punishingblow.jpg" },
      { "name": "Overpower", "imageUrl": "zamimg-icons/ability_meleedamage.jpg" },
      { "name": "Retaliation", "imageUrl": "zamimg-icons/ability_warrior_challange.jpg" },
      { "name": "Sweeping Strikes", "imageUrl": "zamimg-icons/ability_rogue_shadowstrikes.jpg" },
      { "name": "Whirlwind", "imageUrl": "zamimg-icons/spell_whirlwind.jpg" },
      { "name": "Bloodthirst", "imageUrl": "zamimg-icons/spell_nature_bloodlust.jpg" },
      { "name": "Shield Bash", "imageUrl": "zamimg-icons/spell_shield_bash.jpg" },
      { "name": "Disarm", "imageUrl": "zamimg-icons/ability_warrior_disarm.jpg" },
      { "name": "Intervene", "imageUrl": "zamimg-icons/spell_intervene.jpg" },
      { "name": "Last Stand", "imageUrl": "zamimg-icons/spell_holy_ashestoashes.jpg" },
      { "name": "Taunt", "imageUrl": "zamimg-icons/spell_nature_reincarnation.jpg" },
      { "name": "Shield Block", "imageUrl": "zamimg-icons/ability_defend.jpg" },
      { "name": "Shield Wall", "imageUrl": "zamimg-icons/ability_warrior_shieldwall.jpg" },
      { "name": "Intimidating Shout", "imageUrl": "zamimg-icons/ability_golemthunderclap.jpg" },
      { "name": "Challenging Shout", "imageUrl": "zamimg-icons/ability_bullrush.jpg" },
      { "name": "Berserker Rage", "imageUrl": "zamimg-icons/spell_nature_ancestralguardian.jpg" },
      { "name": "Pummel", "imageUrl": "zamimg-icons/inv_gauntlets_04.jpg" },
      { "name": "Shield Slam", "imageUrl": "zamimg-icons/inv_shield_05.jpg" },
      { "name": "Mortal Strike", "imageUrl": "zamimg-icons/ability_warrior_savageblow.jpg" },
      { "name": "Bloodrage", "imageUrl": "zamimg-icons/ability_racial_bloodrage.jpg" },
      { "name": "Slam", "imageUrl": "zamimg-icons/ability_warrior_decisivestrike.jpg" },
      { "name": "Intercept", "imageUrl": "zamimg-icons/ability_rogue_sprint.jpg" },
      { "name": "Concussion Blow", "imageUrl": "zamimg-icons/ability_thunderbolt.jpg" },
      { "name": "Revenge", "imageUrl": "zamimg-icons/ability_warrior_revenge.jpg" },
      { "name": "Recklessness", "imageUrl": "zamimg-icons/ability_criticalstrike.jpg" }
    ],
    "Paladin": [
      { "name": "Holy Light", "imageUrl": "zamimg-icons/spell_holy_light.jpg" },
      { "name": "Hammer of Justice", "imageUrl": "zamimg-icons/inv_hammer_02.jpg" },
      { "name": "Divine Shield", "imageUrl": "zamimg-icons/spell_holy_divineprotection.jpg" },
      { "name": "Flash of Light", "imageUrl": "zamimg-icons/spell_flash_of_light.jpg" },
      { "name": "Seal of Righteousness", "imageUrl": "zamimg-icons/spell_seal_of_righteousness.jpg" },
      { "name": "Consecration", "imageUrl": "zamimg-icons/spell_holy_innerfire.jpg" },
      { "name": "Cleanse", "imageUrl": "zamimg-icons/spell_cleanse.jpg" },
      { "name": "Hand of Protection", "imageUrl": "zamimg-icons/spell_holy_sealofprotection.jpg" },
      { "name": "Hand of Freedom", "imageUrl": "zamimg-icons/spell_holy_sealofvalor.jpg" },
      { "name": "Hand of Sacrifice", "imageUrl": "zamimg-icons/spell_holy_sealofsacrifice.jpg" },
      { "name": "Lay on Hands", "imageUrl": "zamimg-icons/spell_lay_on_hands.jpg" },
      { "name": "Retribution Aura", "imageUrl": "zamimg-icons/spell_retribution_aura.jpg" },
      { "name": "Devotion Aura", "imageUrl": "zamimg-icons/spell_holy_auramastery.jpg" },
      { "name": "Concentration Aura", "imageUrl": "zamimg-icons/spell_holy_auramastery.jpg" },
      { "name": "Sanctity Aura", "imageUrl": "zamimg-icons/spell_holy_auramastery.jpg" },
      { "name": "Seal of Wisdom", "imageUrl": "zamimg-icons/spell_seal_of_wisdom.jpg" },
      { "name": "Seal of Light", "imageUrl": "zamimg-icons/spell_holy_summonlightwell.jpg" },
      { "name": "Righteous Fury", "imageUrl": "zamimg-icons/spell_nature_windfury.jpg" },
      { "name": "Aura of Concentration", "imageUrl": "zamimg-icons/spell_holy_auramastery.jpg" },
      { "name": "Sacred Shield", "imageUrl": "zamimg-icons/inv_shield_19.jpg" },
      { "name": "Judgement", "imageUrl": "zamimg-icons/spell_holy_righteousfury.jpg" },
      { "name": "Seal of Command", "imageUrl": "zamimg-icons/ability_warrior_innerrage.jpg" },
      { "name": "Seal of the Crusader", "imageUrl": "zamimg-icons/spell_holy_holysmite.jpg" },
      { "name": "Blessing of Might", "imageUrl": "zamimg-icons/spell_holy_fistofjustice.jpg" },
      { "name": "Blessing of Wisdom", "imageUrl": "zamimg-icons/spell_holy_sealofwisdom.jpg" },
      { "name": "Blessing of Kings", "imageUrl": "zamimg-icons/spell_magic_magearmor.jpg" },
      { "name": "Blessing of Salvation", "imageUrl": "zamimg-icons/spell_holy_sealofsalvation.jpg" },
      { "name": "Greater Blessing of Might", "imageUrl": "zamimg-icons/spell_holy_greaterblessingofkings.jpg" },
      { "name": "Greater Blessing of Wisdom", "imageUrl": "zamimg-icons/spell_holy_greaterblessingofwisdom.jpg" },
      { "name": "Greater Blessing of Kings", "imageUrl": "zamimg-icons/spell_holy_greaterblessingofkings.jpg" },
      { "name": "Greater Blessing of Salvation", "imageUrl": "zamimg-icons/spell_holy_greaterblessingofsalvation.jpg" },
      { "name": "Turn Undead", "imageUrl": "zamimg-icons/spell_holy_turnundead.jpg" },
      { "name": "Exorcism", "imageUrl": "zamimg-icons/spell_holy_excorcism.jpg" },
      { "name": "Repentance", "imageUrl": "zamimg-icons/spell_holy_prayerofhealing.jpg" },
      { "name": "Divine Favor", "imageUrl": "zamimg-icons/spell_holy_heal.jpg" },
      { "name": "Divine Protection", "imageUrl": "zamimg-icons/spell_holy_devotion.jpg" },
      { "name": "Hammer of Wrath", "imageUrl": "zamimg-icons/ability_thunderclap.jpg" },
      { "name": "Redemption", "imageUrl": "zamimg-icons/spell_holy_resurrection.jpg" }
    ],
    "Hunter": [
      { "name": "Arcane Shot", "imageUrl": "zamimg-icons/spell_arcane_shot.jpg" },
      { "name": "Serpent Sting", "imageUrl": "zamimg-icons/inv_jewelcrafting_rubyserpent.jpg" },
      { "name": "Multi-Shot", "imageUrl": "zamimg-icons/ability_upgrademoonglaive.jpg" },
      { "name": "Aimed Shot", "imageUrl": "zamimg-icons/inv_spear_07.jpg" },
      { "name": "Distracting Shot", "imageUrl": "zamimg-icons/ability_rogue_kidneyshot.jpg" },
      { "name": "Hunter's Mark", "imageUrl": "zamimg-icons/ability_marksmanship.jpg" },
      { "name": "Volley", "imageUrl": "zamimg-icons/ability_marksmanship.jpg" },
      { "name": "Concussive Shot", "imageUrl": "zamimg-icons/ability_rogue_kidneyshot.jpg" },
      { "name": "Wing Clip", "imageUrl": "zamimg-icons/ability_druid_eclipse.jpg" },
      { "name": "Mend Pet", "imageUrl": "zamimg-icons/ability_hunter_mendpet.jpg" },
      { "name": "Call Pet", "imageUrl": "zamimg-icons/ability_hunter_pet_hyena.jpg" },
      { "name": "Dismiss Pet", "imageUrl": "zamimg-icons/ability_hunter_pet_hyena.jpg" },
      { "name": "Tame Beast", "imageUrl": "zamimg-icons/inv_misc_ticket_tarot_beasts_01.jpg" },
      { "name": "Scare Beast", "imageUrl": "zamimg-icons/inv_misc_ticket_tarot_beasts_01.jpg" },
      { "name": "Freezing Trap", "imageUrl": "zamimg-icons/spell_frost_chainsofice.jpg" },
      { "name": "Immolation Trap", "imageUrl": "zamimg-icons/spell_fire_flameshock.jpg" },
      { "name": "Flare", "imageUrl": "zamimg-icons/spell_fire_flare.jpg" },
      { "name": "Viper Sting", "imageUrl": "zamimg-icons/inv_misc_ticket_tarot_twistingnether_01.jpg" },
      { "name": "Scorpid Sting", "imageUrl": "zamimg-icons/ability_hunter_pet_scorpid.jpg" },
      { "name": "Aspect of the Cheetah", "imageUrl": "zamimg-icons/spell_aspect_of_the_cheetah.jpg" }
    ],
    "Rogue": [
      { "name": "Sinister Strike", "imageUrl": "zamimg-icons/spell_shadow_ritualofsacrifice.jpg" },
      { "name": "Eviscerate", "imageUrl": "zamimg-icons/spell_eviscerate.jpg" },
      { "name": "Sap", "imageUrl": "zamimg-icons/spell_sap.jpg" },
      { "name": "Backstab", "imageUrl": "zamimg-icons/ability_backstab.jpg" },
      { "name": "Slice and Dice", "imageUrl": "zamimg-icons/inv_misc_bandage_04.jpg" },
      { "name": "Stealth", "imageUrl": "zamimg-icons/spell_stealth.jpg" },
      { "name": "Sprint", "imageUrl": "zamimg-icons/spell_sprint.jpg" },
      { "name": "Ambush", "imageUrl": "zamimg-icons/spell_ambush.jpg" },
      { "name": "Cheap Shot", "imageUrl": "zamimg-icons/ability_rogue_kidneyshot.jpg" },
      { "name": "Gouge", "imageUrl": "zamimg-icons/ability_gouge.jpg" },
      { "name": "Kick", "imageUrl": "zamimg-icons/spell_kick.jpg" },
      { "name": "Distract", "imageUrl": "zamimg-icons/ability_rogue_distract.jpg" },
      { "name": "Vanish", "imageUrl": "zamimg-icons/spell_vanish.jpg" },
      { "name": "Blind", "imageUrl": "zamimg-icons/spell_shadow_mindsteal.jpg" },
      { "name": "Poisons", "imageUrl": "zamimg-icons/ability_poisons.jpg" },
      { "name": "Feint", "imageUrl": "zamimg-icons/ability_rogue_feint.jpg" },
      { "name": "Riposte", "imageUrl": "zamimg-icons/ability_warrior_riposte.jpg" },
      { "name": "Kidney Shot", "imageUrl": "zamimg-icons/ability_rogue_kidneyshot.jpg" },
      { "name": "Garrote", "imageUrl": "zamimg-icons/spell_garrote.jpg" },
      { "name": "Expose Armor", "imageUrl": "zamimg-icons/spell_fire_firearmor.jpg" }
    ],
    "Priest": [
      { "name": "Heal", "imageUrl": "zamimg-icons/spell_holy_heal.jpg" },
      { "name": "Shadow Word: Pain", "imageUrl": "zamimg-icons/spell_shadow_shadowwordpain.jpg" },
      { "name": "Flash Heal", "imageUrl": "zamimg-icons/spell_holy_flashheal.jpg" },
      { "name": "Mind Blast", "imageUrl": "zamimg-icons/spell_shadow_mindrot.jpg" },
      { "name": "Power Word: Shield", "imageUrl": "zamimg-icons/spell_holy_powerwordshield.jpg" },
      { "name": "Renew", "imageUrl": "zamimg-icons/spell_holy_renew.jpg" },
      { "name": "Smite", "imageUrl": "zamimg-icons/spell_holy_holysmite.jpg" },
      { "name": "Holy Fire", "imageUrl": "zamimg-icons/spell_holy_searinglight.jpg" },
      { "name": "Fear Ward", "imageUrl": "zamimg-icons/spell_nature_guardianward.jpg" },
      { "name": "Mind Soothe", "imageUrl": "zamimg-icons/spell_shadow_mindrot.jpg" },
      { "name": "Shackle Undead", "imageUrl": "zamimg-icons/spell_nature_slow.jpg" },
      { "name": "Dispel Magic", "imageUrl": "zamimg-icons/spell_magic_polymorphchicken.jpg" },
      { "name": "Silence", "imageUrl": "zamimg-icons/spell_silence.jpg" },
      { "name": "Vampiric Embrace", "imageUrl": "zamimg-icons/spell_shadow_vampiricaura.jpg" },
      { "name": "Shadowform", "imageUrl": "zamimg-icons/spell_shadow_shadowform.jpg" },
      { "name": "Holy Nova", "imageUrl": "zamimg-icons/spell_holy_nova.jpg" },
      { "name": "Prayer of Healing", "imageUrl": "zamimg-icons/spell_prayer_of_healing.jpg" },
      { "name": "Circle of Healing", "imageUrl": "zamimg-icons/spell_nature_healingwavegreater.jpg" },
      { "name": "Inner Fire", "imageUrl": "zamimg-icons/spell_holy_innerfire.jpg" },
      { "name": "Fade", "imageUrl": "zamimg-icons/spell_magic_lesserinvisibilty.jpg" },
      { "name": "Greater Heal", "imageUrl": "zamimg-icons/spell_holy_greaterheal.jpg" },
      { "name": "Lesser Heal", "imageUrl": "zamimg-icons/spell_holy_lesserheal.jpg" },
      { "name": "Resurrection", "imageUrl": "zamimg-icons/spell_holy_resurrection.jpg" },
      { "name": "Cure Disease", "imageUrl": "zamimg-icons/spell_holy_nullifydisease.jpg" },
      { "name": "Abolish Disease", "imageUrl": "zamimg-icons/spell_nature_nullifydisease.jpg" },
      { "name": "Mind Control", "imageUrl": "zamimg-icons/spell_shadow_shadowworddominate.jpg" },
      { "name": "Psychic Scream", "imageUrl": "zamimg-icons/spell_shadow_psychicscream.jpg" },
      { "name": "Mana Burn", "imageUrl": "zamimg-icons/spell_shadow_manaburn.jpg" },
      { "name": "Mind Vision", "imageUrl": "zamimg-icons/spell_holy_mindvision.jpg" },
      { "name": "Prayer of Fortitude", "imageUrl": "zamimg-icons/spell_holy_prayeroffortitude.jpg" },
      { "name": "Prayer of Spirit", "imageUrl": "zamimg-icons/spell_holy_prayerofspirit.jpg" },
      { "name": "Divine Spirit", "imageUrl": "zamimg-icons/spell_holy_divinespirit.jpg" },
      { "name": "Power Word: Fortitude", "imageUrl": "zamimg-icons/spell_holy_wordfortitude.jpg" },
      { "name": "Shadow Protection", "imageUrl": "zamimg-icons/spell_shadow_antishadow.jpg" },
      { "name": "Prayer of Shadow Protection", "imageUrl": "zamimg-icons/spell_holy_prayerofshadowprotection.jpg" },
      { "name": "Devouring Plague", "imageUrl": "zamimg-icons/spell_shadow_blackplague.jpg" },
      { "name": "Touch of Weakness", "imageUrl": "zamimg-icons/spell_shadow_deadofnight.jpg" },
      { "name": "Hex of Weakness", "imageUrl": "zamimg-icons/spell_shadow_fingerofdeath.jpg" },
      { "name": "Feedback", "imageUrl": "zamimg-icons/spell_shadow_ritualofsacrifice.jpg" },
      { "name": "Mind Flay", "imageUrl": "zamimg-icons/spell_shadow_siphonmana.jpg" },
      { "name": "Shadow Word: Death", "imageUrl": "zamimg-icons/spell_shadow_demonicfortitude.jpg" }
    ],
    "Shaman": [
      { "name": "Lightning Bolt", "imageUrl": "zamimg-icons/spell_lightning_bolt.jpg" },
      { "name": "Healing Wave", "imageUrl": "zamimg-icons/spell_healing_wave.jpg" },
      { "name": "Chain Lightning", "imageUrl": "zamimg-icons/spell_chain_lightning.jpg" },
      { "name": "Rockbiter Weapon", "imageUrl": "zamimg-icons/inv_weapon_shortblade_25.jpg" },
      { "name": "Earth Shock", "imageUrl": "zamimg-icons/spell_nature_earthshock.jpg" },
      { "name": "Searing Totem", "imageUrl": "zamimg-icons/spell_fire_searingtotem.jpg" },
      { "name": "Ghost Wolf", "imageUrl": "zamimg-icons/inv_chest_wolf.jpg" },
      { "name": "Flame Shock", "imageUrl": "zamimg-icons/spell_fire_flameshock.jpg" },
      { "name": "Frost Shock", "imageUrl": "zamimg-icons/spell_frost_frostshock.jpg" },
      { "name": "Windfury Weapon", "imageUrl": "zamimg-icons/spell_windfury_weapon.jpg" },
      { "name": "Grace of Air Totem", "imageUrl": "zamimg-icons/spell_nature_invisibilitytotem.jpg" },
      { "name": "Stoneskin Totem", "imageUrl": "zamimg-icons/spell_nature_stoneskintotem.jpg" },
      { "name": "Tremor Totem", "imageUrl": "zamimg-icons/spell_nature_tremortotem.jpg" },
      { "name": "Grounding Totem", "imageUrl": "zamimg-icons/spell_nature_groundingtotem.jpg" },
      { "name": "Purge", "imageUrl": "zamimg-icons/spell_purge.jpg" },
      { "name": "Reincarnation", "imageUrl": "zamimg-icons/spell_reincarnation.jpg" },
      { "name": "Ancestral Spirit", "imageUrl": "zamimg-icons/spell_nature_spiritarmor.jpg" },
      { "name": "Water Breathing", "imageUrl": "zamimg-icons/spell_water_breathing.jpg" },
      { "name": "Water Walking", "imageUrl": "zamimg-icons/spell_water_walking.jpg" },
      { "name": "Cure Poison", "imageUrl": "zamimg-icons/ability_poisons.jpg" }
    ],
    "Mage": [
      { "name": "Fireball", "imageUrl": "zamimg-icons/spell_fire_flamebolt.jpg" },
      { "name": "Frostbolt", "imageUrl": "zamimg-icons/spell_frost_frostbolt02.jpg" },
      { "name": "Arcane Blast", "imageUrl": "zamimg-icons/spell_arcane_blast.jpg" },
      { "name": "Polymorph", "imageUrl": "zamimg-icons/spell_polymorph.jpg" },
      { "name": "Blizzard", "imageUrl": "zamimg-icons/spell_frost_icestorm.jpg" },
      { "name": "Ice Barrier", "imageUrl": "zamimg-icons/spell_ice_lament.jpg" },
      { "name": "Scorch", "imageUrl": "zamimg-icons/spell_fire_soulburn.jpg" },
      { "name": "Cone of Cold", "imageUrl": "zamimg-icons/spell_frost_coldhearted.jpg" },
      { "name": "Fire Blast", "imageUrl": "zamimg-icons/spell_fire_fireball.jpg" },
      { "name": "Frost Nova", "imageUrl": "zamimg-icons/spell_frost_frostnova.jpg" },
      { "name": "Ice Lance", "imageUrl": "zamimg-icons/spell_ice_lament.jpg" },
      { "name": "Counterspell", "imageUrl": "zamimg-icons/spell_frost_iceshock.jpg" },
      { "name": "Remove Curse", "imageUrl": "zamimg-icons/spell_holy_removecurse.jpg" },
      { "name": "Arcane Intellect", "imageUrl": "zamimg-icons/spell_arcane_intellect.jpg" },
      { "name": "Dampen Magic", "imageUrl": "zamimg-icons/spell_magic_polymorphchicken.jpg" },
      { "name": "Amplify Magic", "imageUrl": "zamimg-icons/spell_magic_polymorphchicken.jpg" },
      { "name": "Evocation", "imageUrl": "zamimg-icons/spell_nature_purge.jpg" },
      { "name": "Mana Shield", "imageUrl": "zamimg-icons/ability_druid_manatree.jpg" },
      { "name": "Arcane Explosion", "imageUrl": "zamimg-icons/spell_arcane_portalthunderbluff.jpg" },
      { "name": "Slow Fall", "imageUrl": "zamimg-icons/spell_magic_featherfall.jpg" }
    ],
    "Warlock": [
      { "name": "Shadow Bolt", "imageUrl": "zamimg-icons/spell_shadow_shadowbolt.jpg" },
      { "name": "Corruption", "imageUrl": "zamimg-icons/spell_corruption.jpg" },
      { "name": "Immolate", "imageUrl": "zamimg-icons/spell_immolate.jpg" },
      { "name": "Drain Life", "imageUrl": "zamimg-icons/spell_drain_life.jpg" },
      { "name": "Curse of Agony", "imageUrl": "zamimg-icons/spell_holy_removecurse.jpg" },
      { "name": "Summon Succubus", "imageUrl": "zamimg-icons/spell_summon_succubus.jpg" },
      { "name": "Fear", "imageUrl": "zamimg-icons/spell_fear.jpg" },
      { "name": "Siphon Life", "imageUrl": "zamimg-icons/spell_shadow_siphonmana.jpg" },
      { "name": "Rain of Fire", "imageUrl": "zamimg-icons/spell_shadow_rainoffire.jpg" },
      { "name": "Hellfire", "imageUrl": "zamimg-icons/achievement_zone_hellfirepeninsula_01.jpg" },
      { "name": "Soulfire", "imageUrl": "zamimg-icons/spell_fire_fireball02.jpg" },
      { "name": "Shadowburn", "imageUrl": "zamimg-icons/spell_shadow_scorch.jpg" },
      { "name": "Healthstone", "imageUrl": "zamimg-icons/inv_stone_04.jpg" },
      { "name": "Create Soulstone", "imageUrl": "zamimg-icons/spell_shadow_soulgem.jpg" },
      { "name": "Summon Imp", "imageUrl": "zamimg-icons/spell_summon_imp.jpg" },
      { "name": "Summon Voidwalker", "imageUrl": "zamimg-icons/spell_summon_voidwalker.jpg" },
      { "name": "Banish", "imageUrl": "zamimg-icons/spell_shadow_cripple.jpg" },
      { "name": "Enslave Demon", "imageUrl": "zamimg-icons/spell_shadow_enslavedemon.jpg" },
      { "name": "Demonic Sacrifice", "imageUrl": "zamimg-icons/ability_warlock_demonicempowerment.jpg" },
      { "name": "Fel Domination", "imageUrl": "zamimg-icons/spell_fire_felflamestrike.jpg" }
    ],
    "Druid": [
      { "name": "Wrath", "imageUrl": "zamimg-icons/spell_nature_abolishmagic.jpg" },
      { "name": "Regrowth", "imageUrl": "zamimg-icons/spell_nature_resistnature.jpg" },
      { "name": "Moonfire", "imageUrl": "zamimg-icons/spell_nature_starfall.jpg" },
      { "name": "Cat Form", "imageUrl": "zamimg-icons/ability_druid_flightform.jpg" },
      { "name": "Bear Form", "imageUrl": "zamimg-icons/ability_druid_flightform.jpg" },
      { "name": "Healing Touch", "imageUrl": "zamimg-icons/spell_healing_touch.jpg" },
      { "name": "Faerie Fire", "imageUrl": "zamimg-icons/spell_nature_faeriefire.jpg" },
      { "name": "Swipe", "imageUrl": "zamimg-icons/ability_druid_swipe.jpg" },
      { "name": "Thorns", "imageUrl": "zamimg-icons/spell_thorns.jpg" },
      { "name": "Travel Form", "imageUrl": "zamimg-icons/ability_druid_flightform.jpg" },
      { "name": "Prowl", "imageUrl": "zamimg-icons/ability_ambush.jpg" },
      { "name": "Rejuvenation", "imageUrl": "zamimg-icons/spell_rejuvenation.jpg" },
      { "name": "Entangling Roots", "imageUrl": "zamimg-icons/spell_entangling_roots.jpg" },
      { "name": "Growl", "imageUrl": "zamimg-icons/ability_physical_taunt.jpg" },
      { "name": "Bash", "imageUrl": "zamimg-icons/ability_druid_bash.jpg" },
      { "name": "Rip", "imageUrl": "zamimg-icons/ability_warrior_riposte.jpg" },
      { "name": "Shred", "imageUrl": "zamimg-icons/spell_shadow_vampiricaura.jpg" },
      { "name": "Innervate", "imageUrl": "zamimg-icons/spell_nature_lightning.jpg" },
      { "name": "Tranquility", "imageUrl": "zamimg-icons/spell_tranquility.jpg" },
      { "name": "Starfire", "imageUrl": "zamimg-icons/spell_arcane_starfire.jpg" }
    ]
  },
  "TBC Classic": {
    "General": [
      { "name": "PVP Trinket", "imageUrl": "zamimg-icons/inv_jewelry_trinketpvp_02.jpg" },
      { "name": "Will of the Forsaken", "imageUrl": "zamimg-icons/spell_shadow_raisedead.jpg" },
      { "name": "Stoneform", "imageUrl": "zamimg-icons/spell_shadow_unholystrength.jpg" },
      { "name": "Escape Artist", "imageUrl": "zamimg-icons/spell_shadow_charm.jpg" },
      { "name": "Shadowmeld", "imageUrl": "zamimg-icons/ability_ambush.jpg" },
      { "name": "War Stomp", "imageUrl": "zamimg-icons/ability_warstomp.jpg" },
      { "name": "Berserking", "imageUrl": "zamimg-icons/racial_troll_berserk.jpg" },
      { "name": "Arcane Torrent", "imageUrl": "zamimg-icons/spell_shadow_teleport.jpg" },
      { "name": "Gift of the Naaru", "imageUrl": "zamimg-icons/spell_holy_holyprotection.jpg" }
    ],
    "Warrior": [
      { "name": "Mortal Strike (TBC)", "imageUrl": "zamimg-icons/ability_warrior_savageblow.jpg" },
      { "name": "Spell Reflection (TBC)", "imageUrl": "zamimg-icons/spell_nature_guardianward.jpg" },
      { "name": "Shield Slam (TBC)", "imageUrl": "zamimg-icons/inv_shield_19.jpg" },
      { "name": "Heroic Throw (TBC)", "imageUrl": "zamimg-icons/inv_throwingknife_03.jpg" },
      { "name": "Shockwave (TBC)", "imageUrl": "zamimg-icons/ability_warrior_shockwave.jpg" },
      { "name": "Intercept (TBC)", "imageUrl": "zamimg-icons/ability_rogue_sprint.jpg" },
      { "name": "Rallying Cry (TBC)", "imageUrl": "zamimg-icons/ability_warrior_warcry.jpg" },
      { "name": "Bladestorm (TBC)", "imageUrl": "zamimg-icons/ability_warrior_bladestorm.jpg" },
      { "name": "Shattering Throw (TBC)", "imageUrl": "zamimg-icons/inv_throwingknife_03.jpg" },
      { "name": "Cleave (TBC)", "imageUrl": "zamimg-icons/ability_warrior_cleave.jpg" }
    ],
    "Paladin": [
      { "name": "Crusader Strike (TBC)", "imageUrl": "zamimg-icons/spell_holy_crusaderstrike.jpg" },
      { "name": "Avenging Wrath (TBC)", "imageUrl": "zamimg-icons/spell_holy_avenginwrath.jpg" },
      { "name": "Exorcism (TBC)", "imageUrl": "zamimg-icons/spell_holy_excorcism_02.jpg" },
      { "name": "Seal of Blood (TBC)", "imageUrl": "zamimg-icons/ability_racial_bloodrage.jpg" },
      { "name": "Holy Shock (TBC)", "imageUrl": "zamimg-icons/spell_holy_innerfire.jpg" },
      { "name": "Divine Storm (TBC)", "imageUrl": "zamimg-icons/ability_paladin_divinestorm.jpg" },
      { "name": "Hammer of Wrath (TBC)", "imageUrl": "zamimg-icons/spell_paladin_hammerofwrath.jpg" },
      { "name": "Hand of Reckoning (TBC)", "imageUrl": "zamimg-icons/spell_holy_unyieldingfaith.jpg" },
      { "name": "Redemption (TBC)", "imageUrl": "zamimg-icons/spell_holy_redemption.jpg" },
      { "name": "Blessing of Kings (TBC)", "imageUrl": "zamimg-icons/spell_holy_greaterblessingofkings.jpg" }
    ],
    "Hunter": [
      { "name": "Steady Shot (TBC)", "imageUrl": "zamimg-icons/ability_hunter_steadyshot.jpg" },
      { "name": "Kill Command (TBC)", "imageUrl": "zamimg-icons/achievement_bg_kill_on_mount.jpg" },
      { "name": "Feign Death (TBC)", "imageUrl": "zamimg-icons/ability_rogue_feigndeath.jpg" },
      { "name": "Deterrence (TBC)", "imageUrl": "zamimg-icons/ability_whirlwind.jpg" },
      { "name": "Snake Trap (TBC)", "imageUrl": "zamimg-icons/ability_hunter_snaketrap.jpg" },
      { "name": "Mend Pet (TBC)", "imageUrl": "zamimg-icons/ability_hunter_mendpet.jpg" },
      { "name": "Aspect of the Viper (TBC)", "imageUrl": "zamimg-icons/inv_chest_leather_09.jpg" },
      { "name": "Freezing Trap (TBC)", "imageUrl": "zamimg-icons/spell_frost_chainsofice.jpg" },
      { "name": "Flare (TBC)", "imageUrl": "zamimg-icons/spell_fire_flare.jpg" },
      { "name": "Volley (TBC)", "imageUrl": "zamimg-icons/ability_marksmanship.jpg" }
    ],
    "Rogue": [
      { "name": "Mutilate (TBC)", "imageUrl": "zamimg-icons/ability_rogue_shadowstrikes.jpg" },
      { "name": "Cloak of Shadows (TBC)", "imageUrl": "zamimg-icons/ability_rogue_shadowstrikes.jpg" },
      { "name": "Fan of Knives (TBC)", "imageUrl": "zamimg-icons/ability_rogue_fanofknives.jpg" },
      { "name": "Stealth (TBC)", "imageUrl": "zamimg-icons/ability_stealth.jpg" },
      { "name": "Shadowstep (TBC)", "imageUrl": "zamimg-icons/ability_rogue_shadowstep.jpg" },
      { "name": "Killing Spree (TBC)", "imageUrl": "zamimg-icons/ability_rogue_murderspree.jpg" },
      { "name": "Ambush (TBC)", "imageUrl": "zamimg-icons/ability_ambush.jpg" },
      { "name": "Cheap Shot (TBC)", "imageUrl": "zamimg-icons/ability_rogue_kidneyshot.jpg" },
      { "name": "Gouge (TBC)", "imageUrl": "zamimg-icons/ability_gouge.jpg" },
      { "name": "Kick (TBC)", "imageUrl": "zamimg-icons/ability_kick.jpg" }
    ],
    "Priest": [
      { "name": "Power Word: Shield (TBC)", "imageUrl": "zamimg-icons/spell_holy_powerwordshield.jpg" },
      { "name": "Mind Flay (TBC)", "imageUrl": "zamimg-icons/spell_shadow_siphonmana.jpg" },
      { "name": "Prayer of Mending (TBC)", "imageUrl": "zamimg-icons/spell_holy_prayerofmendingtga.jpg" },
      { "name": "Shadowfiend (TBC)", "imageUrl": "zamimg-icons/spell_shadow_shadowfiend.jpg" },
      { "name": "Circle of Healing (TBC)", "imageUrl": "zamimg-icons/spell_nature_healingwavegreater.jpg" },
      { "name": "Penance (TBC)", "imageUrl": "zamimg-icons/spell_holy_penance.jpg" },
      { "name": "Binding Heal (TBC)", "imageUrl": "zamimg-icons/spell_holy_heal.jpg" },
      { "name": "Greater Heal (TBC)", "imageUrl": "zamimg-icons/spell_holy_greaterheal.jpg" },
      { "name": "Holy Nova (TBC)", "imageUrl": "zamimg-icons/spell_holy_innerfire.jpg" },
      { "name": "Shadow Word: Death (TBC)", "imageUrl": "zamimg-icons/spell_shadow_demonicfortitude.jpg" }
    ],
    "Shaman": [
      { "name": "Bloodlust (TBC)", "imageUrl": "zamimg-icons/spell_nature_bloodlust.jpg" },
      { "name": "Heroism (TBC)", "imageUrl": "zamimg-icons/spell_nature_bloodlust.jpg" },
      { "name": "Water Shield (TBC)", "imageUrl": "zamimg-icons/ability_shaman_watershield.jpg" },
      { "name": "Lightning Shield (TBC)", "imageUrl": "zamimg-icons/inv_shield_19.jpg" },
      { "name": "Chain Heal (TBC)", "imageUrl": "zamimg-icons/spell_nature_healingwavegreater.jpg" },
      { "name": "Earthbind Totem (TBC)", "imageUrl": "zamimg-icons/spell_nature_strengthofearthtotem02.jpg" },
      { "name": "Wind Shear (TBC)", "imageUrl": "zamimg-icons/spell_nature_windfury.jpg" },
      { "name": "Stormstrike (TBC)", "imageUrl": "zamimg-icons/ability_shaman_stormstrike.jpg" },
      { "name": "Lava Burst (TBC)", "imageUrl": "zamimg-icons/spell_shaman_lavaburst.jpg" },
      { "name": "Spirit Link Totem (TBC)", "imageUrl": "zamimg-icons/spell_shaman_spiritlink.jpg" }
    ],
    "Mage": [
      { "name": "Blizzard (TBC)", "imageUrl": "zamimg-icons/spell_frost_icestorm.jpg" },
      { "name": "Molten Armor (TBC)", "imageUrl": "zamimg-icons/spell_fire_firearmor.jpg" },
      { "name": "Spellsteal (TBC)", "imageUrl": "zamimg-icons/spell_arcane_arcane02.jpg" },
      { "name": "Slow (TBC)", "imageUrl": "zamimg-icons/spell_nature_slow.jpg" },
      { "name": "Ice Lance (TBC)", "imageUrl": "zamimg-icons/spell_frost_frostblast.jpg" },
      { "name": "Dragon's Breath (TBC)", "imageUrl": "zamimg-icons/spell_nature_corrosivebreath.jpg" },
      { "name": "Arcane Barrage (TBC)", "imageUrl": "zamimg-icons/spell_arcane_portalthunderbluff.jpg" },
      { "name": "Flamestrike (TBC)", "imageUrl": "zamimg-icons/spell_fire_felflamestrike.jpg" },
      { "name": "Ice Floes (TBC)", "imageUrl": "zamimg-icons/spell_ice_lament.jpg" },
      { "name": "Mirror Image (TBC)", "imageUrl": "zamimg-icons/spell_nature_mirrorimage.jpg" }
    ],
    "Warlock": [
      { "name": "Seed of Corruption (TBC)", "imageUrl": "zamimg-icons/spell_shadow_seedofdestruction.jpg" },
      { "name": "Unstable Affliction (TBC)", "imageUrl": "zamimg-icons/spell_shadow_unstableaffliction_3.jpg" },
      { "name": "Summon Felguard (TBC)", "imageUrl": "zamimg-icons/spell_shadow_summonfelguard.jpg" },
      { "name": "Fear (TBC)", "imageUrl": "zamimg-icons/spell_nature_strengthofearthtotem02.jpg" },
      { "name": "Corruption (TBC)", "imageUrl": "zamimg-icons/spell_shadow_abominationexplosion.jpg" },
      { "name": "Soul Fire (TBC)", "imageUrl": "zamimg-icons/spell_fire_fireball02.jpg" },
      { "name": "Chaos Bolt (TBC)", "imageUrl": "zamimg-icons/spell_fire_felchaosblast.jpg" },
      { "name": "Conflagrate (TBC)", "imageUrl": "zamimg-icons/spell_fire_fireball.jpg" },
      { "name": "Incinerate (TBC)", "imageUrl": "zamimg-icons/spell_fire_burnout.jpg" },
      { "name": "Rain of Fire (TBC)", "imageUrl": "zamimg-icons/spell_shadow_rainoffire.jpg" }
    ],
    "Druid": [
      { "name": "Swiftmend (TBC)", "imageUrl": "zamimg-icons/inv_relics_idolofrejuvenation.jpg" },
      { "name": "Mangle (TBC)", "imageUrl": "zamimg-icons/ability_druid_mangle2.jpg" },
      { "name": "Lifebloom (TBC)", "imageUrl": "zamimg-icons/inv_misc_herb_felblossom.jpg" },
      { "name": "Cyclone (TBC)", "imageUrl": "zamimg-icons/spell_nature_cyclone.jpg" },
      { "name": "Feral Charge (TBC)", "imageUrl": "zamimg-icons/spell_frost_manarecharge.jpg" },
      { "name": "Growl (TBC)", "imageUrl": "zamimg-icons/ability_physical_taunt.jpg" },
      { "name": "Nourish (TBC)", "imageUrl": "zamimg-icons/ability_druid_nourish.jpg" },
      { "name": "Force of Nature (TBC)", "imageUrl": "zamimg-icons/spell_nature_guardianward.jpg" },
      { "name": "Barkskin (TBC)", "imageUrl": "zamimg-icons/spell_nature_stoneclawtotem.jpg" },
      { "name": "Faerie Fire (TBC)", "imageUrl": "zamimg-icons/spell_nature_faeriefire.jpg" }
    ],
    "Death Knight": [
      { "name": "Death Coil", "imageUrl": "zamimg-icons/spell_death_coil.jpg" },
      { "name": "Icy Touch", "imageUrl": "zamimg-icons/spell_icy_touch.jpg" },
      { "name": "Plague Strike", "imageUrl": "zamimg-icons/spell_plague_strike.jpg" },
      { "name": "Blood Strike", "imageUrl": "zamimg-icons/spell_blood_strike.jpg" },
      { "name": "Heart Strike", "imageUrl": "zamimg-icons/spell_heart_strike.jpg" },
      { "name": "Obliterate", "imageUrl": "zamimg-icons/spell_obliterate.jpg" },
      { "name": "Frost Strike", "imageUrl": "zamimg-icons/spell_frost_strike.jpg" },
      { "name": "Rune Strike", "imageUrl": "zamimg-icons/spell_rune_strike.jpg" },
      { "name": "Death and Decay", "imageUrl": "zamimg-icons/spell_death_and_decay.jpg" },
      { "name": "Raise Dead", "imageUrl": "zamimg-icons/spell_raise_dead.jpg" }
    ]
  },
  "MoP Classic": {
    "General": [
      { "name": "PVP Trinket", "imageUrl": "zamimg-icons/inv_jewelry_trinketpvp_02.jpg" },
      { "name": "Will of the Forsaken", "imageUrl": "zamimg-icons/spell_shadow_raisedead.jpg" },
      { "name": "Stoneform", "imageUrl": "zamimg-icons/spell_shadow_unholystrength.jpg" },
      { "name": "Escape Artist", "imageUrl": "zamimg-icons/spell_shadow_charm.jpg" },
      { "name": "Shadowmeld", "imageUrl": "zamimg-icons/ability_ambush.jpg" },
      { "name": "War Stomp", "imageUrl": "zamimg-icons/ability_warstomp.jpg" },
      { "name": "Berserking", "imageUrl": "zamimg-icons/racial_troll_berserk.jpg" },
      { "name": "Arcane Torrent", "imageUrl": "zamimg-icons/spell_shadow_teleport.jpg" },
      { "name": "Gift of the Naaru", "imageUrl": "zamimg-icons/spell_holy_holyprotection.jpg" },
      { "name": "Quaking Palm", "imageUrl": "zamimg-icons/ability_monk_palmstrike.jpg" }
    ],
    "Warrior": [
      { "name": "Storm Bolt", "imageUrl": "zamimg-icons/spell_nature_lightning.jpg" },
      { "name": "Colossus Smash", "imageUrl": "zamimg-icons/ability_warrior_colossussmash.jpg" },
      { "name": "Safeguard", "imageUrl": "zamimg-icons/ability_warrior_vigilance.jpg" },
      { "name": "Bloodbath", "imageUrl": "zamimg-icons/spell_shadow_bloodboil.jpg" },
      { "name": "Shockwave", "imageUrl": "zamimg-icons/ability_warrior_shockwave.jpg" },
      { "name": "Dragon Roar", "imageUrl": "zamimg-icons/spell_fire_felrainoffire.jpg" },
      { "name": "Avatar", "imageUrl": "zamimg-icons/spell_holy_divinespirit.jpg" },
      { "name": "Warbringer", "imageUrl": "zamimg-icons/ability_warrior_charge.jpg" },
      { "name": "Second Wind", "imageUrl": "zamimg-icons/spell_nature_windfury.jpg" },
      { "name": "Impending Victory", "imageUrl": "zamimg-icons/spell_impending_victory.jpg" }
    ],
    "Monk": [
      { "name": "Tiger Palm", "imageUrl": "zamimg-icons/spell_tiger_palm.jpg" },
      { "name": "Chi Burst", "imageUrl": "zamimg-icons/achievement_boss_murmur.jpg" },
      { "name": "Blackout Kick", "imageUrl": "zamimg-icons/spell_blackout_kick.jpg" },
      { "name": "Expel Harm", "imageUrl": "zamimg-icons/ability_monk_expelharm.jpg" },
      { "name": "Spinning Crane Kick", "imageUrl": "zamimg-icons/spell_spinning_crane_kick.jpg" },
      { "name": "Renewing Mist", "imageUrl": "zamimg-icons/spell_renewing_mist.jpg" },
      { "name": "Jab", "imageUrl": "zamimg-icons/spell_jab.jpg" },
      { "name": "Rising Sun Kick", "imageUrl": "zamimg-icons/spell_rising_sun_kick.jpg" },
      { "name": "Transcendence", "imageUrl": "zamimg-icons/monk_stance_redcrane.jpg" },
      { "name": "Fizzle", "imageUrl": "zamimg-icons/spell_nature_acid_01.jpg" },
      { "name": "Leg Sweep", "imageUrl": "zamimg-icons/ability_monk_legsweep.jpg" },
      { "name": "Paralysis", "imageUrl": "zamimg-icons/spell_paralysis.jpg" },
      { "name": "Drunken Haze", "imageUrl": "zamimg-icons/spell_brew_dark.jpg" },
      { "name": "Guard", "imageUrl": "zamimg-icons/spell_nature_guardianward.jpg" },
      { "name": "Chi Torpedo", "imageUrl": "zamimg-icons/achievement_boss_murmur.jpg" },
      { "name": "Touch of Death", "imageUrl": "zamimg-icons/spell_shadow_deathcoil.jpg" },
      { "name": "Storm, Earth, and Fire", "imageUrl": "zamimg-icons/spell_shaman_stormearthfire.jpg" },
      { "name": "Zen Meditation", "imageUrl": "zamimg-icons/spell_frost_frozencore.jpg" },
      { "name": "Healing Sphere", "imageUrl": "zamimg-icons/spell_nature_healingwavegreater.jpg" },
      { "name": "Crackling Jade Lightning", "imageUrl": "zamimg-icons/spell_crackling_jade_lightning.jpg" }
    ],
    "Paladin": [
      { "name": "Light of Dawn", "imageUrl": "zamimg-icons/spell_paladin_lightofdawn.jpg" },
      { "name": "Execution Sentence", "imageUrl": "zamimg-icons/spell_paladin_executionsentence.jpg" },
      { "name": "Hand of Purity", "imageUrl": "zamimg-icons/spell_holy_persuitofjustice.jpg" },
      { "name": "Holy Avenger", "imageUrl": "zamimg-icons/spell_holy_avenginwrath.jpg" },
      { "name": "Sacred Shield", "imageUrl": "zamimg-icons/inv_shield_19.jpg" },
      { "name": "Hand of Justice", "imageUrl": "zamimg-icons/spell_holy_sealofmight.jpg" },
      { "name": "Clemency", "imageUrl": "zamimg-icons/spell_holy_renew.jpg" },
      { "name": "Selfless Healer", "imageUrl": "zamimg-icons/spell_holy_heal.jpg" },
      { "name": "Holy Prism", "imageUrl": "zamimg-icons/spell_paladin_holyprism.jpg" },
      { "name": "Hand of Protection", "imageUrl": "zamimg-icons/spell_holy_sealofprotection.jpg" }
    ],
    "Hunter": [
      { "name": "Cobra Shot", "imageUrl": "zamimg-icons/ability_hunter_cobrashot.jpg" },
      { "name": "Stampede", "imageUrl": "zamimg-icons/ability_hunter_pet_bear.jpg" },
      { "name": "Binding Shot", "imageUrl": "zamimg-icons/spell_frost_chainsofice.jpg" },
      { "name": "Explosive Shot", "imageUrl": "zamimg-icons/ability_hunter_explosiveshot.jpg" },
      { "name": "Steady Shot", "imageUrl": "zamimg-icons/ability_hunter_steadyshot.jpg" },
      { "name": "Multi-Shot", "imageUrl": "zamimg-icons/ability_upgrademoonglaive.jpg" },
      { "name": "Kill Command", "imageUrl": "zamimg-icons/achievement_bg_kill_on_mount.jpg" },
      { "name": "Feign Death", "imageUrl": "zamimg-icons/ability_rogue_feigndeath.jpg" },
      { "name": "Deterrence", "imageUrl": "zamimg-icons/ability_whirlwind.jpg" },
      { "name": "Mend Pet", "imageUrl": "zamimg-icons/ability_hunter_mendpet.jpg" }
    ],
    "Rogue": [
      { "name": "Ambush", "imageUrl": "zamimg-icons/ability_ambush.jpg" },
      { "name": "Shuriken Toss", "imageUrl": "zamimg-icons/inv_throwingknife_04.jpg" },
      { "name": "Crimson Tempest", "imageUrl": "zamimg-icons/spell_shadow_bloodboil.jpg" },
      { "name": "Killing Spree", "imageUrl": "zamimg-icons/ability_rogue_murderspree.jpg" },
      { "name": "Shadow Reflection", "imageUrl": "zamimg-icons/spell_shadow_charm.jpg" },
      { "name": "Preparation", "imageUrl": "zamimg-icons/spell_shadow_antishadow.jpg" },
      { "name": "Adrenaline Rush", "imageUrl": "zamimg-icons/ability_bullrush.jpg" },
      { "name": "Eviscerate", "imageUrl": "zamimg-icons/ability_rogue_eviscerate.jpg" },
      { "name": "Sinister Strike", "imageUrl": "zamimg-icons/spell_shadow_ritualofsacrifice.jpg" },
      { "name": "Stealth", "imageUrl": "zamimg-icons/ability_stealth.jpg" }
    ],
    "Priest": [
      { "name": "Divine Star", "imageUrl": "zamimg-icons/spell_priest_divinestar.jpg" },
      { "name": "Cascade", "imageUrl": "zamimg-icons/spell_holy_prayerofhealing.jpg" },
      { "name": "Spirit Shell", "imageUrl": "zamimg-icons/spell_nature_spiritarmor.jpg" },
      { "name": "Chakra", "imageUrl": "zamimg-icons/spell_priest_chakra.jpg" },
      { "name": "Desperate Prayer", "imageUrl": "zamimg-icons/spell_holy_prayerofmendingtga.jpg" },
      { "name": "From Darkness, Comes Light", "imageUrl": "zamimg-icons/spell_shadow_twilight.jpg" },
      { "name": "Phantasm", "imageUrl": "zamimg-icons/spell_shadow_charm.jpg" },
      { "name": "Heal", "imageUrl": "zamimg-icons/spell_holy_heal.jpg" },
      { "name": "Shadow Word: Pain", "imageUrl": "zamimg-icons/spell_shadow_shadowwordpain.jpg" },
      { "name": "Flash Heal", "imageUrl": "zamimg-icons/spell_holy_flashheal.jpg" }
    ],
    "Death Knight": [
      { "name": "Death Siphon", "imageUrl": "zamimg-icons/spell_shadow_lifedrain02.jpg" },
      { "name": "Conversion", "imageUrl": "zamimg-icons/spell_shadow_soulleech_3.jpg" },
      { "name": "Gargoyle Strike", "imageUrl": "zamimg-icons/spell_gargoyle_strike.jpg" },
      { "name": "Lichborne", "imageUrl": "zamimg-icons/spell_shadow_raisedead.jpg" },
      { "name": "Purgatory", "imageUrl": "zamimg-icons/spell_shadow_demonicfortitude.jpg" },
      { "name": "Anti-Magic Zone", "imageUrl": "zamimg-icons/achievement_zone_easternkingdoms_01.jpg" },
      { "name": "Gorefiend's Grasp", "imageUrl": "zamimg-icons/ability_mage_wintersgrasp.jpg" },
      { "name": "Death Coil", "imageUrl": "zamimg-icons/spell_death_coil.jpg" },
      { "name": "Icy Touch", "imageUrl": "zamimg-icons/spell_icy_touch.jpg" },
      { "name": "Plague Strike", "imageUrl": "zamimg-icons/spell_plague_strike.jpg" }
    ],
    "Shaman": [
      { "name": "Ascendance", "imageUrl": "zamimg-icons/spell_fire_elementaldevastation.jpg" },
      { "name": "Elemental Blast", "imageUrl": "zamimg-icons/spell_nature_lightningoverload.jpg" },
      { "name": "Healing Stream Totem", "imageUrl": "zamimg-icons/inv_spear_04.jpg" },
      { "name": "Unleash Elements", "imageUrl": "zamimg-icons/spell_shaman_unleashweapon_life.jpg" },
      { "name": "Spirit Walk", "imageUrl": "zamimg-icons/spell_frost_windwalkon.jpg" },
      { "name": "Primal Elementalist", "imageUrl": "zamimg-icons/inv_elemental_primal_earth.jpg" },
      { "name": "Ancestral Guidance", "imageUrl": "zamimg-icons/spell_nature_spiritarmor.jpg" },
      { "name": "Lightning Bolt", "imageUrl": "zamimg-icons/spell_fire_firebolt.jpg" },
      { "name": "Healing Wave", "imageUrl": "zamimg-icons/spell_healing_wave.jpg" },
      { "name": "Chain Lightning", "imageUrl": "zamimg-icons/inv_chest_chain_07.jpg" }
    ],
    "Mage": [
      { "name": "Alter Time", "imageUrl": "zamimg-icons/spell_mage_altertime.jpg" },
      { "name": "Ice Floes", "imageUrl": "zamimg-icons/spell_ice_lament.jpg" },
      { "name": "Invocation", "imageUrl": "zamimg-icons/spell_shadow_teleport.jpg" },
      { "name": "Living Bomb", "imageUrl": "zamimg-icons/spell_fire_selfdestruct.jpg" },
      { "name": "Presence of Mind", "imageUrl": "zamimg-icons/spell_nature_enchantarmor.jpg" },
      { "name": "Cauterize", "imageUrl": "zamimg-icons/spell_fire_rune.jpg" },
      { "name": "Deep Freeze", "imageUrl": "zamimg-icons/spell_frost_stun.jpg" },
      { "name": "Fireball", "imageUrl": "zamimg-icons/spell_fire_flamebolt.jpg" },
      { "name": "Frostbolt", "imageUrl": "zamimg-icons/spell_frost_frostbolt02.jpg" },
      { "name": "Arcane Blast", "imageUrl": "zamimg-icons/spell_arcane_portalthunderbluff.jpg" }
    ],
    "Warlock": [
      { "name": "Dark Soul", "imageUrl": "zamimg-icons/spell_shadow_demonicpact.jpg" },
      { "name": "Mortal Coil", "imageUrl": "zamimg-icons/spell_shadow_deathcoil.jpg" },
      { "name": "Kil'jaeden's Cunning", "imageUrl": "zamimg-icons/spell_shadow_demonicpact.jpg" },
      { "name": "Grimoire of Supremacy", "imageUrl": "zamimg-icons/spell_shadow_demonicpact.jpg" },
      { "name": "Soul Swap", "imageUrl": "zamimg-icons/spell_shadow_soulleech_1.jpg" },
      { "name": "Unending Resolve", "imageUrl": "zamimg-icons/spell_shadow_demonicfortitude.jpg" },
      { "name": "Demonic Gateway", "imageUrl": "zamimg-icons/ability_warlock_demonicempowerment.jpg" },
      { "name": "Shadow Bolt", "imageUrl": "zamimg-icons/spell_shadow_shadowbolt.jpg" },
      { "name": "Corruption", "imageUrl": "zamimg-icons/spell_shadow_abominationexplosion.jpg" },
      { "name": "Immolate", "imageUrl": "zamimg-icons/spell_fire_immolation.jpg" }
    ],
    "Druid": [
      { "name": "Symbiosis", "imageUrl": "zamimg-icons/spell_druid_symbiosis.jpg" },
      { "name": "Incarnation", "imageUrl": "zamimg-icons/spell_druid_incarnation.jpg" },
      { "name": "Cenarion Ward", "imageUrl": "zamimg-icons/spell_nature_guardianward.jpg" },
      { "name": "Soul of the Forest", "imageUrl": "zamimg-icons/inv_chest_leather_09.jpg" },
      { "name": "Nature's Vigil", "imageUrl": "zamimg-icons/spell_nature_natureguardian.jpg" },
      { "name": "Wild Charge", "imageUrl": "zamimg-icons/spell_frost_manarecharge.jpg" },
      { "name": "Displacer Beast", "imageUrl": "zamimg-icons/inv_misc_ticket_tarot_beasts_01.jpg" },
      { "name": "Wrath", "imageUrl": "zamimg-icons/spell_nature_abolishmagic.jpg" },
      { "name": "Regrowth", "imageUrl": "zamimg-icons/spell_nature_resistnature.jpg" },
      { "name": "Moonfire", "imageUrl": "zamimg-icons/spell_nature_starfall.jpg" }
    ]
  },
  "Retail": {
    "General": [
      { "name": "PVP Trinket", "imageUrl": "zamimg-icons/inv_jewelry_trinketpvp_02.jpg" },
      { "name": "Will of the Forsaken", "imageUrl": "zamimg-icons/spell_shadow_raisedead.jpg" },
      { "name": "Stoneform", "imageUrl": "zamimg-icons/spell_shadow_unholystrength.jpg" },
      { "name": "Escape Artist", "imageUrl": "zamimg-icons/spell_shadow_charm.jpg" },
      { "name": "Shadowmeld", "imageUrl": "zamimg-icons/ability_ambush.jpg" },
      { "name": "War Stomp", "imageUrl": "zamimg-icons/ability_warstomp.jpg" },
      { "name": "Berserking", "imageUrl": "zamimg-icons/racial_troll_berserk.jpg" },
      { "name": "Arcane Torrent", "imageUrl": "zamimg-icons/spell_shadow_teleport.jpg" },
      { "name": "Gift of the Naaru", "imageUrl": "zamimg-icons/spell_holy_holyprotection.jpg" },
      { "name": "Spatial Rift", "imageUrl": "zamimg-icons/spell_arcane_blink.jpg" },
      { "name": "Fireblood", "imageUrl": "zamimg-icons/spell_fire_burnout.jpg" }
    ],
    "Warrior": [
      { "name": "Overpower", "imageUrl": "zamimg-icons/ability_meleedamage.jpg" },
      { "name": "Rallying Cry", "imageUrl": "zamimg-icons/ability_warrior_rallyingcry.jpg" },
      { "name": "Bladestorm", "imageUrl": "zamimg-icons/ability_warrior_bladestorm.jpg" },
      { "name": "Recklessness", "imageUrl": "zamimg-icons/ability_criticalstrike.jpg" },
      { "name": "Charge", "imageUrl": "zamimg-icons/spell_charge.jpg" },
      { "name": "Execute", "imageUrl": "zamimg-icons/inv_sword_48.jpg" },
      { "name": "Shield Block", "imageUrl": "zamimg-icons/inv_shield_19.jpg" },
      { "name": "Whirlwind", "imageUrl": "zamimg-icons/ability_whirlwind.jpg" },
      { "name": "Mortal Strike", "imageUrl": "zamimg-icons/ability_warrior_savageblow.jpg" },
      { "name": "Slam", "imageUrl": "zamimg-icons/ability_warrior_decisivestrike.jpg" }
    ],
    "Demon Hunter": [
      { "name": "Blade Dance", "imageUrl": "zamimg-icons/spell_blade_dance.jpg" },
      { "name": "Eye Beam", "imageUrl": "zamimg-icons/spell_eye_beam.jpg" },
      { "name": "Immolation Aura", "imageUrl": "zamimg-icons/spell_holy_auramastery.jpg" },
      { "name": "Metamorphosis", "imageUrl": "zamimg-icons/spell_metamorphosis.jpg" },
      { "name": "Fel Rush", "imageUrl": "zamimg-icons/spell_fire_felflamestrike.jpg" },
      { "name": "Blur", "imageUrl": "zamimg-icons/spell_magic_lesserinvisibilty.jpg" },
      { "name": "Chaos Strike", "imageUrl": "zamimg-icons/ability_demonhunter_chaosstrike.jpg" },
      { "name": "Throw Glaive", "imageUrl": "zamimg-icons/inv_throwingknife_03.jpg" },
      { "name": "Disrupt", "imageUrl": "zamimg-icons/spell_shadow_cripple.jpg" },
      { "name": "Darkness", "imageUrl": "zamimg-icons/spell_shadow_charm.jpg" },
      { "name": "Spectral Sight", "imageUrl": "zamimg-icons/spell_nature_farsight.jpg" },
      { "name": "Soul Cleave", "imageUrl": "zamimg-icons/spell_shadow_soulleech_1.jpg" },
      { "name": "Imprison", "imageUrl": "zamimg-icons/spell_shadow_mindsteal.jpg" },
      { "name": "Netherwalk", "imageUrl": "zamimg-icons/spell_warlock_demonsoul.jpg" },
      { "name": "Vengeful Retreat", "imageUrl": "zamimg-icons/ability_rogue_sprint.jpg" },
      { "name": "Consume Magic", "imageUrl": "zamimg-icons/spell_magic_polymorphchicken.jpg" },
      { "name": "Sigil of Flame", "imageUrl": "zamimg-icons/spell_demonhunter_sigilofflame.jpg" },
      { "name": "Spirit Bomb", "imageUrl": "zamimg-icons/spell_nature_spiritarmor.jpg" },
      { "name": "Fel Devastation", "imageUrl": "zamimg-icons/classic_spell_fire_elementaldevastation.jpg" },
      { "name": "The Hunt", "imageUrl": "zamimg-icons/spell_the_hunt.jpg" }
    ],
    "Evoker": [
      { "name": "Devastation", "imageUrl": "zamimg-icons/classic_spell_fire_elementaldevastation.jpg" },
      { "name": "Preservation", "imageUrl": "zamimg-icons/spell_nature_healingwavegreater.jpg" },
      { "name": "Hover", "imageUrl": "zamimg-icons/ability_druid_flightform.jpg" },
      { "name": "Dream Breath", "imageUrl": "zamimg-icons/spell_nature_corrosivebreath.jpg" },
      { "name": "Living Flame", "imageUrl": "zamimg-icons/spell_fire_flameshock.jpg" },
      { "name": "Emerald Blossom", "imageUrl": "zamimg-icons/inv_misc_gem_emerald_01.jpg" },
      { "name": "Fire Breath", "imageUrl": "zamimg-icons/spell_fire_fireball.jpg" },
      { "name": "Azure Strike", "imageUrl": "zamimg-icons/spell_frost_frostbolt02.jpg" },
      { "name": "Disintegrate", "imageUrl": "zamimg-icons/spell_nature_wispsplode.jpg" },
      { "name": "Echo", "imageUrl": "zamimg-icons/spell_shadow_charm.jpg" },
      { "name": "Zephyr", "imageUrl": "zamimg-icons/spell_nature_cyclone.jpg" },
      { "name": "Cauterizing Flame", "imageUrl": "zamimg-icons/spell_fire_sealoffire.jpg" },
      { "name": "Obsidian Scales", "imageUrl": "zamimg-icons/inv_misc_monsterscales_04.jpg" },
      { "name": "Deep Breath", "imageUrl": "zamimg-icons/spell_nature_corrosivebreath.jpg" },
      { "name": "Tip the Scales", "imageUrl": "zamimg-icons/inv_chest_leather_09.jpg" },
      { "name": "Temporal Anomaly", "imageUrl": "zamimg-icons/spell_arcane_blink.jpg" },
      { "name": "Rewind", "imageUrl": "zamimg-icons/spell_arcane_blink.jpg" },
      { "name": "Dragonrage", "imageUrl": "zamimg-icons/spell_fire_felrainoffire.jpg" },
      { "name": "Evoker Utility 1", "imageUrl": "zamimg-icons/spell_nature_lightningoverload.jpg" },
      { "name": "Evoker Utility 2", "imageUrl": "zamimg-icons/spell_frost_frostbolt02.jpg" }
    ],
    "Paladin": [
      { "name": "Word of Glory", "imageUrl": "zamimg-icons/spell_holy_holybolt.jpg" },
      { "name": "Shield of the Righteous", "imageUrl": "zamimg-icons/inv_chest_leather_09.jpg" },
      { "name": "Divine Toll", "imageUrl": "zamimg-icons/spell_holy_prayerofhealing02.jpg" },
      { "name": "Wake of Ashes", "imageUrl": "zamimg-icons/spell_holy_avenginwrath.jpg" },
      { "name": "Crusader Strike", "imageUrl": "zamimg-icons/spell_holy_crusaderstrike.jpg" },
      { "name": "Hammer of Wrath", "imageUrl": "zamimg-icons/inv_hammer_02.jpg" },
      { "name": "Lay on Hands", "imageUrl": "zamimg-icons/spell_fire_playingwithfire.jpg" },
      { "name": "Avenging Wrath", "imageUrl": "zamimg-icons/spell_holy_avenginwrath.jpg" },
      { "name": "Holy Shock", "imageUrl": "zamimg-icons/spell_holy_innerfire.jpg" },
      { "name": "Divine Protection", "imageUrl": "zamimg-icons/spell_holy_devotion.jpg" }
    ],
    "Hunter": [
      { "name": "Kill Shot", "imageUrl": "zamimg-icons/ability_hunter_assassinate2.jpg" },
      { "name": "Tar Trap", "imageUrl": "zamimg-icons/spell_frost_frostarmor.jpg" },
      { "name": "Aspect of the Cheetah", "imageUrl": "zamimg-icons/spell_aspect_of_the_cheetah.jpg" },
      { "name": "Barrage", "imageUrl": "zamimg-icons/ability_hunter_rapidregeneration.jpg" },
      { "name": "Steady Shot", "imageUrl": "zamimg-icons/ability_hunter_steadyshot.jpg" },
      { "name": "Multi-Shot", "imageUrl": "zamimg-icons/ability_upgrademoonglaive.jpg" },
      { "name": "Disengage", "imageUrl": "zamimg-icons/ability_rogue_feint.jpg" },
      { "name": "Explosive Shot", "imageUrl": "zamimg-icons/ability_rogue_kidneyshot.jpg" },
      { "name": "Cobra Shot", "imageUrl": "zamimg-icons/ability_hunter_cobrashot.jpg" },
      { "name": "Freezing Trap", "imageUrl": "zamimg-icons/spell_frost_chainsofice.jpg" }
    ],
    "Rogue": [
      { "name": "Shadowstrike", "imageUrl": "zamimg-icons/ability_rogue_shadowstrike.jpg" },
      { "name": "Kidney Shot", "imageUrl": "zamimg-icons/ability_rogue_kidneyshot.jpg" },
      { "name": "Vanish", "imageUrl": "zamimg-icons/ability_vanish.jpg" },
      { "name": "Slice and Dice", "imageUrl": "zamimg-icons/inv_misc_bandage_04.jpg" },
      { "name": "Eviscerate", "imageUrl": "zamimg-icons/ability_rogue_eviscerate.jpg" },
      { "name": "Blind", "imageUrl": "zamimg-icons/spell_shadow_mindsteal.jpg" },
      { "name": "Shadow Dance", "imageUrl": "zamimg-icons/ability_rogue_shadowdance.jpg" },
      { "name": "Ambush", "imageUrl": "zamimg-icons/ability_ambush.jpg" },
      { "name": "Cheap Shot", "imageUrl": "zamimg-icons/ability_rogue_kidneyshot.jpg" },
      { "name": "Gouge", "imageUrl": "zamimg-icons/ability_gouge.jpg" }
    ],
    "Priest": [
      { "name": "Power Word: Radiance", "imageUrl": "zamimg-icons/spell_priest_power-word.jpg" },
      { "name": "Mind Games", "imageUrl": "zamimg-icons/spell_shadow_charm.jpg" },
      { "name": "Holy Word: Serenity", "imageUrl": "zamimg-icons/spell_holy_innerfire.jpg" },
      { "name": "Shadow Crash", "imageUrl": "zamimg-icons/spell_shadow_shadowwordpain.jpg" },
      { "name": "Heal", "imageUrl": "zamimg-icons/spell_holy_heal.jpg" },
      { "name": "Renew", "imageUrl": "zamimg-icons/spell_holy_renew.jpg" },
      { "name": "Flash Heal", "imageUrl": "zamimg-icons/spell_holy_flashheal.jpg" },
      { "name": "Smite", "imageUrl": "zamimg-icons/spell_holy_holysmite.jpg" },
      { "name": "Holy Fire", "imageUrl": "zamimg-icons/spell_holy_searinglight.jpg" },
      { "name": "Prayer of Mending", "imageUrl": "zamimg-icons/spell_holy_prayerofmendingtga.jpg" }
    ],
    "Death Knight": [
      { "name": "Death Strike", "imageUrl": "zamimg-icons/spell_deathknight_deathstrike.jpg" },
      { "name": "Raise Dead", "imageUrl": "zamimg-icons/spell_shadow_nightofthedead.jpg" },
      { "name": "Abomination Limb", "imageUrl": "zamimg-icons/spell_shadow_raisedead.jpg" },
      { "name": "Chains of Ice", "imageUrl": "zamimg-icons/spell_ice_lament.jpg" },
      { "name": "Obliterate", "imageUrl": "zamimg-icons/spell_obliterate.jpg" },
      { "name": "Empower Rune Weapon", "imageUrl": "zamimg-icons/inv_weapon_shortblade_25.jpg" },
      { "name": "Death's Advance", "imageUrl": "zamimg-icons/spell_deathknight_deathstrike.jpg" },
      { "name": "Icy Touch", "imageUrl": "zamimg-icons/spell_icy_touch.jpg" },
      { "name": "Plague Strike", "imageUrl": "zamimg-icons/spell_plague_strike.jpg" },
      { "name": "Blood Strike", "imageUrl": "zamimg-icons/spell_blood_strike.jpg" }
    ],
    "Shaman": [
      { "name": "Lava Burst", "imageUrl": "zamimg-icons/spell_shaman_lavaburst.jpg" },
      { "name": "Spirit Link Totem", "imageUrl": "zamimg-icons/spell_shaman_spiritlink.jpg" },
      { "name": "Feral Spirit", "imageUrl": "zamimg-icons/spell_nature_spiritarmor.jpg" },
      { "name": "Chain Heal", "imageUrl": "zamimg-icons/spell_nature_healingwavegreater.jpg" },
      { "name": "Stormstrike", "imageUrl": "zamimg-icons/ability_shaman_stormstrike.jpg" },
      { "name": "Healing Stream Totem", "imageUrl": "zamimg-icons/inv_spear_04.jpg" },
      { "name": "Wind Shear", "imageUrl": "zamimg-icons/spell_nature_windfury.jpg" },
      { "name": "Lightning Bolt", "imageUrl": "zamimg-icons/spell_fire_firebolt.jpg" },
      { "name": "Healing Wave", "imageUrl": "zamimg-icons/spell_healing_wave.jpg" },
      { "name": "Chain Lightning", "imageUrl": "zamimg-icons/inv_chest_chain_07.jpg" }
    ],
    "Mage": [
      { "name": "Comet Storm", "imageUrl": "zamimg-icons/spell_frost_icestorm.jpg" },
      { "name": "Ray of Frost", "imageUrl": "zamimg-icons/spell_frost_frostbolt.jpg" },
      { "name": "Shifting Power", "imageUrl": "zamimg-icons/spell_arcane_arcane04.jpg" },
      { "name": "Time Warp", "imageUrl": "zamimg-icons/ability_mage_timewarp.jpg" },
      { "name": "Fireball", "imageUrl": "zamimg-icons/spell_fire_flamebolt.jpg" },
      { "name": "Frostbolt", "imageUrl": "zamimg-icons/spell_frost_frostbolt02.jpg" },
      { "name": "Arcane Blast", "imageUrl": "zamimg-icons/spell_arcane_portalthunderbluff.jpg" },
      { "name": "Polymorph", "imageUrl": "zamimg-icons/spell_magic_polymorphchicken.jpg" },
      { "name": "Blizzard", "imageUrl": "zamimg-icons/spell_frost_icestorm.jpg" },
      { "name": "Ice Barrier", "imageUrl": "zamimg-icons/spell_ice_lament.jpg" }
    ],
    "Warlock": [
      { "name": "Malefic Rapture", "imageUrl": "zamimg-icons/spell_shadow_demonicfortitude.jpg" },
      { "name": "Summon Demonic Tyrant", "imageUrl": "zamimg-icons/spell_holy_summonlightwell.jpg" },
      { "name": "Soul Rot", "imageUrl": "zamimg-icons/ability_rogue_garrote.jpg" },
      { "name": "Grimoire of Sacrifice", "imageUrl": "zamimg-icons/spell_holy_sealofsacrifice.jpg" },
      { "name": "Shadow Bolt", "imageUrl": "zamimg-icons/spell_shadow_shadowbolt.jpg" },
      { "name": "Corruption", "imageUrl": "zamimg-icons/spell_shadow_abominationexplosion.jpg" },
      { "name": "Immolate", "imageUrl": "zamimg-icons/spell_fire_immolation.jpg" },
      { "name": "Drain Life", "imageUrl": "zamimg-icons/ability_druid_treeoflife.jpg" },
      { "name": "Curse of Agony", "imageUrl": "zamimg-icons/spell_holy_removecurse.jpg" },
      { "name": "Summon Succubus", "imageUrl": "zamimg-icons/spell_holy_summonlightwell.jpg" }
    ],
    "Monk": [
      { "name": "Fists of Fury", "imageUrl": "zamimg-icons/monk_ability_fistoffury.jpg" },
      { "name": "Invoke Niuzao, the Black Ox", "imageUrl": "zamimg-icons/inv_chest_leather_09.jpg" },
      { "name": "Vivify", "imageUrl": "zamimg-icons/ability_monk_vivify.jpg" },
      { "name": "Crackling Jade Lightning", "imageUrl": "zamimg-icons/spell_nature_lightningoverload.jpg" },
      { "name": "Tiger Palm", "imageUrl": "zamimg-icons/spell_tiger_palm.jpg" },
      { "name": "Blackout Kick", "imageUrl": "zamimg-icons/spell_blackout_kick.jpg" },
      { "name": "Expel Harm", "imageUrl": "zamimg-icons/ability_monk_expelharm.jpg" },
      { "name": "Rising Sun Kick", "imageUrl": "zamimg-icons/inv_qirajidol_sun.jpg" },
      { "name": "Transcendence", "imageUrl": "zamimg-icons/monk_stance_redcrane.jpg" },
      { "name": "Zen Meditation", "imageUrl": "zamimg-icons/spell_frost_frozencore.jpg" }
    ],
    "Druid": [
      { "name": "Convoke the Spirits", "imageUrl": "zamimg-icons/spell_nature_forceofnature.jpg" },
      { "name": "Adaptive Swarm", "imageUrl": "zamimg-icons/spell_shadow_carrionswarm.jpg" },
      { "name": "Wild Growth", "imageUrl": "zamimg-icons/ability_druid_flourish.jpg" },
      { "name": "Ferocious Bite", "imageUrl": "zamimg-icons/ability_hunter_ferociousinspiration.jpg" },
      { "name": "Wrath", "imageUrl": "zamimg-icons/spell_nature_abolishmagic.jpg" },
      { "name": "Regrowth", "imageUrl": "zamimg-icons/spell_nature_resistnature.jpg" },
      { "name": "Moonfire", "imageUrl": "zamimg-icons/spell_nature_starfall.jpg" },
      { "name": "Cat Form", "imageUrl": "zamimg-icons/ability_druid_flightform.jpg" },
      { "name": "Bear Form", "imageUrl": "zamimg-icons/ability_druid_flightform.jpg" },
      { "name": "Healing Touch", "imageUrl": "zamimg-icons/spell_nature_healingwavegreater.jpg" }
    ]
  }
};